### ISSUE TITLE
Is there a way to return content as is, rather than converting it to JSON?

### ISSUE THREAD

**Issue by behrangsa** [imrefazekas/connect-rest#10]
In particular I like to render response as XML, but right now it is getting wrapped inside double quotes.

**Comment by jongeho1** [comment]
@imrefazekas - should the headers take precedence when making the decision to stringify? It seems like you'll stringify based on the rest functions content type, https://github.com/imrefazekas/connect-rest/blob/master/lib/connect-rest.js#L140.

If one overrides the headers content type or omits in the rest function, then the content type will always be application/json. This is fine in case of omission; however, if one sets the headers content type "text/csv", then the results will be stringified. It seems like the rest functions content type designation cascades down by design and defaults to application/json. If that was true, then you'd overwrite the headers of the rest function instead of checking for presence and honoring. If there is an easy way to do this using this module, then please me know. The use case would be accepting a format path or query parameter via the rest function and making the content type decision within a single rest function.

Let me know if you have any questions.
@jongeho1
